title = "Ciclismo a lo grande"
baseURL = "https://sbarguil.github.io/ciclismo_a_fondo/"
languageCode = "en-us"
theme = "ananke"
#themesDir = "../.."
#resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
cannonycalURL = true

[languages]
  [languages.en]
    title = "Ciclismo a lo grande"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Disciplina, Determinación, Dedicación y Cuuidado de los Detalles"
  facebook = "https://twitter.com/GoHugoIO"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = "https://twitter.com/GoHugoIO"
  youtube = "https://twitter.com/GoHugoIO"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  commentoEnable = true
  show_reading_time = true
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/metodo.jpg"
  recent_posts_number = 3